name: "Default Prechecks Unix"

on:
  pull_request:
    branches: [ master, alpha ]
    paths-ignore:
      - "*.md"
      - "!unix/**"
      - "!unix-alpha/**"
      - "unix/prechecks/**"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: Ubuntu Default Prechecks
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
          architecture: x64

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      - name: Install flake8
        run: pip install flake8

      ## Check linting ##
      - name: Run flake8 linter
        working-directory: unix
        run: flake8 ./src --config ./setup.cfg
      
      ## Check linting for alpha ##
      - name: Run flake8 linter
        working-directory: unix-alpha
        run: flake8 ./src --config ./setup.cfg
