name: PyPI Upload MS Alpha

on:
  push:
    branches:
      - alpha
      - pranav/improve-pypi-release

jobs:
  machine_stats:
    name: Machine Stats PyPI Upload Alpha
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: unix-alpha

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
          architecture: x64

      - name: Install build and twine
        run: |
          python -m pip install build twine

      - name: Build a binary wheel and a source tarball
        run: |
          python -m build --sdist --wheel --outdir dist/ .

      - name: Upload to PyPI via Twine
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN_ALPHA_PRANAV }}
        run: |
          twine upload --verbose -u '__token__' dist/*
